# Generated by Django 2.0.1 on 2018-10-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_detail', '0002_auto_20181018_0704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
